M48
; DRILL file {KiCad 7.0.5-0} date 2024 April 27, Saturday 19:15:10
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-04-27T19:15:10+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5-0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X72.605Y-64.11
X72.605Y-69.89
T2
X75.6Y-82.5
X82.4Y-82.5
T0
M30
