M48
; DRILL file {KiCad 7.0.5-0} date 2024 April 28, Sunday 23:55:42
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-04-28T23:55:42+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5-0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
%
G90
G05
T1
X72.605Y-64.11
X72.605Y-69.89
T2
X75.6Y-82.5
X82.4Y-82.5
T3
X70.167Y-81.75
X70.333Y-53.333
T0
M30
